export const countryData = [
  {
    id: 1,
    countryName: "Andorra",
    countryName_KR: "안도라",
    countryCode: "AD",
  },
  {
    id: 2,
    countryName: "United Arab Emirates",
    countryName_KR: "아랍에미리트",
    countryCode: "AE",
  },
  {
    id: 3,
    countryName: "Afghanistan",
    countryName_KR: "아프가니스탄",
    countryCode: "AF",
  },
  {
    id: 4,
    countryName: "Ant is stupid",
    countryName_KR: "앤티가 바부다",
    countryCode: "AG",
  },
  {
    id: 5,
    countryName: "Cherry blossoms",
    countryName_KR: "앵귈라",
    countryCode: "AI",
  },
  {
    id: 6,
    countryName: "Albania",
    countryName_KR: "알바니아",
    countryCode: "AL",
  },
  {
    id: 7,
    countryName: "Armenia",
    countryName_KR: "아르메니아",
    countryCode: "AM",
  },
  { id: 8, countryName: "Angola", countryName_KR: "앙골라", countryCode: "AO" },
  {
    id: 9,
    countryName: "Antarctica",
    countryName_KR: "남극",
    countryCode: "AQ",
  },
  {
    id: 10,
    countryName: "Argentina",
    countryName_KR: "아르헨티나",
    countryCode: "AR",
  },
  {
    id: 11,
    countryName: "American Samoa",
    countryName_KR: "아메리칸사모아",
    countryCode: "AS",
  },
  {
    id: 12,
    countryName: "Austria",
    countryName_KR: "오스트리아",
    countryCode: "AT",
  },
  {
    id: 13,
    countryName: "Australia",
    countryName_KR: "오스트레일리아",
    countryCode: "AU",
  },
  {
    id: 14,
    countryName: "Aruba, please",
    countryName_KR: "아루바",
    countryCode: "AW",
  },
  {
    id: 15,
    countryName: "Holland Islands",
    countryName_KR: "올란드 제도",
    countryCode: "AX",
  },
  {
    id: 16,
    countryName: "Azerbaijan",
    countryName_KR: "아제르바이잔",
    countryCode: "AZ",
  },
  {
    id: 17,
    countryName: "Bosnia and Herzegovina",
    countryName_KR: "보스니아 헤르체고비나",
    countryCode: "BA",
  },
  {
    id: 18,
    countryName: "Barbados",
    countryName_KR: "바베이도스",
    countryCode: "BB",
  },
  {
    id: 19,
    countryName: "Bangladesh",
    countryName_KR: "방글라데시",
    countryCode: "BD",
  },
  {
    id: 20,
    countryName: "Belgium",
    countryName_KR: "벨기에",
    countryCode: "BE",
  },
  {
    id: 21,
    countryName: "Burkina Faso",
    countryName_KR: "부르키나파소",
    countryCode: "BF",
  },
  {
    id: 22,
    countryName: "Bulgaria",
    countryName_KR: "불가리아",
    countryCode: "BG",
  },
  {
    id: 23,
    countryName: "Bahrain",
    countryName_KR: "바레인",
    countryCode: "BH",
  },
  {
    id: 24,
    countryName: "Burundi",
    countryName_KR: "부룬디",
    countryCode: "BI",
  },
  { id: 25, countryName: "Benin", countryName_KR: "베냉", countryCode: "BJ" },
  {
    id: 26,
    countryName: "Saint-Barthélémy",
    countryName_KR: "생바르텔레미",
    countryCode: "BL",
  },
  {
    id: 27,
    countryName: "Bermuda",
    countryName_KR: "버뮤다",
    countryCode: "BM",
  },
  {
    id: 28,
    countryName: "Brunei",
    countryName_KR: "브루나이",
    countryCode: "BN",
  },
  {
    id: 29,
    countryName: "Bolivia",
    countryName_KR: "볼리비아",
    countryCode: "BO",
  },
  {
    id: 30,
    countryName: "Bonneres Island",
    countryName_KR: "보네르섬",
    countryCode: "BQ",
  },
  {
    id: 31,
    countryName: "Brazil",
    countryName_KR: "브라질",
    countryCode: "BR",
  },
  {
    id: 32,
    countryName: "the Bahamas",
    countryName_KR: "바하마",
    countryCode: "BS",
  },
  { id: 33, countryName: "butane", countryName_KR: "부탄", countryCode: "BT" },
  {
    id: 34,
    countryName: "the island of Bubes",
    countryName_KR: "부베섬",
    countryCode: "BV",
  },
  {
    id: 35,
    countryName: "Botswana",
    countryName_KR: "보츠와나",
    countryCode: "BW",
  },
  {
    id: 36,
    countryName: "Belarus",
    countryName_KR: "벨라루스",
    countryCode: "BY",
  },
  {
    id: 37,
    countryName: "Belize",
    countryName_KR: "벨리즈",
    countryCode: "BZ",
  },
  {
    id: 38,
    countryName: "Canada",
    countryName_KR: "캐나다",
    countryCode: "CA",
  },
  {
    id: 39,
    countryName: "Cocos Islands",
    countryName_KR: "코코스 제도",
    countryCode: "CC",
  },
  {
    id: 40,
    countryName: "Democratic Republic of the Congo",
    countryName_KR: "콩고 민주 공화국",
    countryCode: "CD",
  },
  {
    id: 41,
    countryName: "Central African Republic",
    countryName_KR: "중앙아프리카 공화국",
    countryCode: "CF",
  },
  {
    id: 42,
    countryName: "Republic of the Congo",
    countryName_KR: "콩고 공화국",
    countryCode: "CG",
  },
  {
    id: 43,
    countryName: "Switzerland",
    countryName_KR: "스위스",
    countryCode: "CH",
  },
  {
    id: 44,
    countryName: "Ivory Coast",
    countryName_KR: "코트디부아르",
    countryCode: "CI",
  },
  {
    id: 45,
    countryName: "Cook Islands",
    countryName_KR: "쿡 제도",
    countryCode: "CK",
  },
  { id: 46, countryName: "Chile", countryName_KR: "칠레", countryCode: "CL" },
  {
    id: 47,
    countryName: "Cameroon",
    countryName_KR: "카메룬",
    countryCode: "CM",
  },
  { id: 48, countryName: "China", countryName_KR: "중국", countryCode: "CN" },
  {
    id: 49,
    countryName: "Colombia",
    countryName_KR: "콜롬비아",
    countryCode: "CO",
  },
  {
    id: 50,
    countryName: "Costa Rica",
    countryName_KR: "코스타리카",
    countryCode: "CR",
  },
  { id: 51, countryName: "Cuba", countryName_KR: "쿠바", countryCode: "CU" },
  {
    id: 52,
    countryName: "Cabo Verde",
    countryName_KR: "카보베르데",
    countryCode: "CV",
  },
  {
    id: 53,
    countryName: "Curaçao",
    countryName_KR: "퀴라소",
    countryCode: "CW",
  },
  {
    id: 54,
    countryName: "Christmas Island",
    countryName_KR: "크리스마스섬",
    countryCode: "CX",
  },
  {
    id: 55,
    countryName: "Cyprus",
    countryName_KR: "키프로스",
    countryCode: "CY",
  },
  {
    id: 56,
    countryName: "Czech Republic",
    countryName_KR: "체코",
    countryCode: "CZ",
  },
  { id: 57, countryName: "Germany", countryName_KR: "독일", countryCode: "DE" },
  {
    id: 58,
    countryName: "Djibouti",
    countryName_KR: "지부티",
    countryCode: "DJ",
  },
  {
    id: 59,
    countryName: "Denmark",
    countryName_KR: "덴마크",
    countryCode: "DK",
  },
  {
    id: 60,
    countryName: "Union of Dominicans",
    countryName_KR: "도미니카 연방",
    countryCode: "DM",
  },
  {
    id: 61,
    countryName: "Dominican Republic",
    countryName_KR: "도미니카 공화국",
    countryCode: "DO",
  },
  {
    id: 62,
    countryName: "Algeria",
    countryName_KR: "알제리",
    countryCode: "DZ",
  },
  {
    id: 63,
    countryName: "Ecuador",
    countryName_KR: "에콰도르",
    countryCode: "EC",
  },
  {
    id: 64,
    countryName: "Estonia",
    countryName_KR: "에스토니아",
    countryCode: "EE",
  },
  {
    id: 65,
    countryName: "Egypt.",
    countryName_KR: "이집트",
    countryCode: "EG",
  },
  {
    id: 66,
    countryName: "Make a narrative",
    countryName_KR: "서사하라",
    countryCode: "EH",
  },
  {
    id: 67,
    countryName: "Eritrea",
    countryName_KR: "에리트레아",
    countryCode: "ER",
  },
  { id: 68, countryName: "Spain", countryName_KR: "스페인", countryCode: "ES" },
  {
    id: 69,
    countryName: "Ethiopia",
    countryName_KR: "에티오피아",
    countryCode: "ET",
  },
  {
    id: 70,
    countryName: "Finland",
    countryName_KR: "핀란드",
    countryCode: "FI",
  },
  { id: 71, countryName: "Fiji", countryName_KR: "피지", countryCode: "FJ" },
  {
    id: 72,
    countryName: "Falkland Islands",
    countryName_KR: "포클랜드 제도",
    countryCode: "FK",
  },
  {
    id: 73,
    countryName: "Federation of Micronesia",
    countryName_KR: "미크로네시아 연방",
    countryCode: "FM",
  },
  {
    id: 74,
    countryName: "Faroe Islands",
    countryName_KR: "페로 제도",
    countryCode: "FO",
  },
  {
    id: 75,
    countryName: "France",
    countryName_KR: "프랑스",
    countryCode: "FR",
  },
  { id: 76, countryName: "Gabon", countryName_KR: "가봉", countryCode: "GA" },
  {
    id: 77,
    countryName: "Great Britain",
    countryName_KR: "영국",
    countryCode: "GB",
  },
  {
    id: 78,
    countryName: "Grenada",
    countryName_KR: "그레나다",
    countryCode: "GD",
  },
  {
    id: 79,
    countryName: "Georgia",
    countryName_KR: "조지아",
    countryCode: "GE",
  },
  {
    id: 80,
    countryName: "Guiana",
    countryName_KR: "기아나",
    countryCode: "GF",
  },
  {
    id: 81,
    countryName: "Guernsey Island",
    countryName_KR: "건지섬",
    countryCode: "GG",
  },
  { id: 82, countryName: "Ghana", countryName_KR: "가나", countryCode: "GH" },
  {
    id: 83,
    countryName: "Gibraltar",
    countryName_KR: "지브롤터",
    countryCode: "GI",
  },
  {
    id: 84,
    countryName: "Greenland",
    countryName_KR: "그린란드",
    countryCode: "GL",
  },
  {
    id: 85,
    countryName: "Gambia",
    countryName_KR: "감비아",
    countryCode: "GM",
  },
  { id: 86, countryName: "Guinea", countryName_KR: "기니", countryCode: "GN" },
  {
    id: 87,
    countryName: "Guadeloupe",
    countryName_KR: "과들루프",
    countryCode: "GP",
  },
  {
    id: 88,
    countryName: "Equatorial Guinea",
    countryName_KR: "적도 기니",
    countryCode: "GQ",
  },
  {
    id: 89,
    countryName: "Greece",
    countryName_KR: "그리스",
    countryCode: "GR",
  },
  {
    id: 90,
    countryName: "South Georgia South Sandwich Islands",
    countryName_KR: "사우스조지아 사우스샌드위치 제도",
    countryCode: "GS",
  },
  {
    id: 91,
    countryName: "Guatemala",
    countryName_KR: "과테말라",
    countryCode: "GT",
  },
  { id: 92, countryName: "Guam", countryName_KR: "괌", countryCode: "GU" },
  {
    id: 93,
    countryName: "Guinea-Bissau",
    countryName_KR: "기니비사우",
    countryCode: "GW",
  },
  {
    id: 94,
    countryName: "Guyana",
    countryName_KR: "가이아나",
    countryCode: "GY",
  },
  {
    id: 95,
    countryName: "Hong Kong",
    countryName_KR: "홍콩",
    countryCode: "HK",
  },
  {
    id: 96,
    countryName: "Heard MacDonald Islands",
    countryName_KR: "허드 맥도널드 제도",
    countryCode: "HM",
  },
  {
    id: 97,
    countryName: "Honduras",
    countryName_KR: "온두라스",
    countryCode: "HN",
  },
  {
    id: 98,
    countryName: "Croatia",
    countryName_KR: "크로아티아",
    countryCode: "HR",
  },
  { id: 99, countryName: "Haiti", countryName_KR: "아이티", countryCode: "HT" },
  {
    id: 100,
    countryName: "Hungary",
    countryName_KR: "헝가리",
    countryCode: "HU",
  },
  {
    id: 101,
    countryName: "Indonesia",
    countryName_KR: "인도네시아",
    countryCode: "ID",
  },
  {
    id: 102,
    countryName: "Ireland",
    countryName_KR: "아일랜드",
    countryCode: "IE",
  },
  {
    id: 103,
    countryName: "Israel",
    countryName_KR: "이스라엘",
    countryCode: "IL",
  },
  {
    id: 104,
    countryName: "Isle of Man",
    countryName_KR: "맨섬",
    countryCode: "IM",
  },
  { id: 105, countryName: "India", countryName_KR: "인도", countryCode: "IN" },
  {
    id: 106,
    countryName: "the British Indian Ocean region",
    countryName_KR: "영국령 인도양 지역",
    countryCode: "IO",
  },
  { id: 107, countryName: "Iraq", countryName_KR: "이라크", countryCode: "IQ" },
  { id: 108, countryName: "Iran", countryName_KR: "이란", countryCode: "IR" },
  {
    id: 109,
    countryName: "Iceland",
    countryName_KR: "아이슬란드",
    countryCode: "IS",
  },
  {
    id: 110,
    countryName: "Italy",
    countryName_KR: "이탈리아",
    countryCode: "IT",
  },
  {
    id: 111,
    countryName: "Jersey Island",
    countryName_KR: "저지섬",
    countryCode: "JE",
  },
  {
    id: 112,
    countryName: "Jamaica",
    countryName_KR: "자메이카",
    countryCode: "JM",
  },
  {
    id: 113,
    countryName: "Jordan",
    countryName_KR: "요르단",
    countryCode: "JO",
  },
  { id: 114, countryName: "Japan", countryName_KR: "일본", countryCode: "JP" },
  { id: 115, countryName: "Kenya", countryName_KR: "케냐", countryCode: "KE" },
  {
    id: 116,
    countryName: "Kyrgyzstan",
    countryName_KR: "키르기스스탄",
    countryCode: "KG",
  },
  {
    id: 117,
    countryName: "Cambodia",
    countryName_KR: "캄보디아",
    countryCode: "KH",
  },
  {
    id: 118,
    countryName: "Kiribati",
    countryName_KR: "키리바시",
    countryCode: "KI",
  },
  {
    id: 119,
    countryName: "Comoros",
    countryName_KR: "코모로",
    countryCode: "KM",
  },
  {
    id: 120,
    countryName: "St. Kitts and Nevis",
    countryName_KR: "세인트키츠 네비스",
    countryCode: "KN",
  },
  {
    id: 122,
    countryName: "Republic of Korea",
    countryName_KR: "대한민국",
    countryCode: "KR",
  },
  {
    id: 123,
    countryName: "Kuwait",
    countryName_KR: "쿠웨이트",
    countryCode: "KW",
  },
  {
    id: 124,
    countryName: "Cayman Islands",
    countryName_KR: "케이맨 제도",
    countryCode: "KY",
  },
  {
    id: 125,
    countryName: "Kazakhstan",
    countryName_KR: "카자흐스탄",
    countryCode: "KZ",
  },
  { id: 126, countryName: "Laos", countryName_KR: "라오스", countryCode: "LA" },
  {
    id: 127,
    countryName: "Lebanon",
    countryName_KR: "레바논",
    countryCode: "LB",
  },
  {
    id: 128,
    countryName: "Saint Lucia",
    countryName_KR: "세인트루시아",
    countryCode: "LC",
  },
  {
    id: 129,
    countryName: "Sri Lanka",
    countryName_KR: "스리랑카",
    countryCode: "LK",
  },
  {
    id: 130,
    countryName: "Liechtenstein",
    countryName_KR: "리히텐슈타인",
    countryCode: "LI",
  },
  {
    id: 131,
    countryName: "Liberia",
    countryName_KR: "라이베리아",
    countryCode: "LR",
  },
  {
    id: 132,
    countryName: "Lesotho",
    countryName_KR: "레소토",
    countryCode: "LS",
  },
  {
    id: 133,
    countryName: "Lithuania",
    countryName_KR: "리투아니아",
    countryCode: "LT",
  },
  {
    id: 134,
    countryName: "Luxembourg",
    countryName_KR: "룩셈부르크",
    countryCode: "LU",
  },
  {
    id: 135,
    countryName: "Latvia",
    countryName_KR: "라트비아",
    countryCode: "LV",
  },
  {
    id: 136,
    countryName: "Libya",
    countryName_KR: "리비아",
    countryCode: "LY",
  },
  {
    id: 137,
    countryName: "Morocco",
    countryName_KR: "모로코",
    countryCode: "MA",
  },
  {
    id: 138,
    countryName: "Monaco",
    countryName_KR: "모나코",
    countryCode: "MC",
  },
  {
    id: 139,
    countryName: "Moldova",
    countryName_KR: "몰도바",
    countryCode: "MD",
  },
  {
    id: 140,
    countryName: "Montenegro",
    countryName_KR: "몬테네그로",
    countryCode: "ME",
  },
  {
    id: 141,
    countryName: "Saint-Martin",
    countryName_KR: "생마르탱",
    countryCode: "MF",
  },
  {
    id: 142,
    countryName: "Madagascar.",
    countryName_KR: "마다가스카르",
    countryCode: "MG",
  },
  {
    id: 143,
    countryName: "Marshall Islands",
    countryName_KR: "마셜 제도",
    countryCode: "MH",
  },
  {
    id: 144,
    countryName: "North Macedonia",
    countryName_KR: "북마케도니아",
    countryCode: "MK",
  },
  { id: 145, countryName: "Mali", countryName_KR: "말리", countryCode: "ML" },
  {
    id: 146,
    countryName: "Myanmar",
    countryName_KR: "미얀마",
    countryCode: "MM",
  },
  {
    id: 147,
    countryName: "Mongolia",
    countryName_KR: "몽골",
    countryCode: "MN",
  },
  {
    id: 148,
    countryName: "Macau",
    countryName_KR: "마카오",
    countryCode: "MO",
  },
  {
    id: 149,
    countryName: "Northern Mariana Islands",
    countryName_KR: "북마리아나 제도",
    countryCode: "MP",
  },
  {
    id: 150,
    countryName: "Martinique",
    countryName_KR: "마르티니크",
    countryCode: "MQ",
  },
  {
    id: 151,
    countryName: "Mauritania",
    countryName_KR: "모리타니",
    countryCode: "MR",
  },
  {
    id: 152,
    countryName: "Montserrat",
    countryName_KR: "몬트세랫",
    countryCode: "MS",
  },
  { id: 153, countryName: "Malta", countryName_KR: "몰타", countryCode: "MT" },
  {
    id: 154,
    countryName: "Mauritius",
    countryName_KR: "모리셔스",
    countryCode: "MU",
  },
  {
    id: 155,
    countryName: "Maldives",
    countryName_KR: "몰디브",
    countryCode: "MV",
  },
  {
    id: 156,
    countryName: "Malawi",
    countryName_KR: "말라위",
    countryCode: "MW",
  },
  {
    id: 157,
    countryName: "Mexico",
    countryName_KR: "멕시코",
    countryCode: "MX",
  },
  {
    id: 158,
    countryName: "Malaysia",
    countryName_KR: "말레이시아",
    countryCode: "MY",
  },
  {
    id: 159,
    countryName: "Mozambique",
    countryName_KR: "모잠비크",
    countryCode: "MZ",
  },
  {
    id: 160,
    countryName: "Namibia",
    countryName_KR: "나미비아",
    countryCode: "NA",
  },
  {
    id: 161,
    countryName: "Nouvelle Caledoni",
    countryName_KR: "누벨칼레도니",
    countryCode: "NC",
  },
  {
    id: 162,
    countryName: "Niger",
    countryName_KR: "니제르",
    countryCode: "NE",
  },
  {
    id: 163,
    countryName: "Norfolk Island",
    countryName_KR: "노퍽섬",
    countryCode: "NF",
  },
  {
    id: 164,
    countryName: "Nigeria",
    countryName_KR: "나이지리아",
    countryCode: "NG",
  },
  {
    id: 165,
    countryName: "Nicaragua",
    countryName_KR: "니카라과",
    countryCode: "NI",
  },
  {
    id: 166,
    countryName: "Netherlands",
    countryName_KR: "네덜란드",
    countryCode: "NL",
  },
  {
    id: 167,
    countryName: "Norway",
    countryName_KR: "노르웨이",
    countryCode: "NO",
  },
  { id: 168, countryName: "Nepal", countryName_KR: "네팔", countryCode: "NP" },
  {
    id: 169,
    countryName: "Nauru",
    countryName_KR: "나우루",
    countryCode: "NR",
  },
  { id: 170, countryName: "niue", countryName_KR: "니우에", countryCode: "NU" },
  {
    id: 171,
    countryName: "New Zealand",
    countryName_KR: "뉴질랜드",
    countryCode: "NZ",
  },
  {
    id: 172,
    countryName: "arrogance",
    countryName_KR: "오만",
    countryCode: "OM",
  },
  {
    id: 173,
    countryName: "Panama",
    countryName_KR: "파나마",
    countryCode: "PA",
  },
  { id: 174, countryName: "Peru", countryName_KR: "페루", countryCode: "PE" },
  {
    id: 175,
    countryName: "French Polynesia",
    countryName_KR: "프랑스령 폴리네시아",
    countryCode: "PF",
  },
  { id: 176, countryName: "Guinea", countryName_KR: "기니", countryCode: "PG" },
  {
    id: 177,
    countryName: "Philippines",
    countryName_KR: "필리핀",
    countryCode: "PH",
  },
  {
    id: 178,
    countryName: "Pakistan",
    countryName_KR: "파키스탄",
    countryCode: "PK",
  },
  {
    id: 179,
    countryName: "Poland",
    countryName_KR: "폴란드",
    countryCode: "PL",
  },
  {
    id: 180,
    countryName: "Saint-Pierre Micleon",
    countryName_KR: "생피에르 미클롱",
    countryCode: "PM",
  },
  {
    id: 181,
    countryName: "Pitcairn Islands",
    countryName_KR: "핏케언 제도",
    countryCode: "PN",
  },
  {
    id: 182,
    countryName: "Puerto Rico",
    countryName_KR: "푸에르토리코",
    countryCode: "PR",
  },
  {
    id: 183,
    countryName: "Palestine",
    countryName_KR: "팔레스타인",
    countryCode: "PS",
  },
  {
    id: 184,
    countryName: "Portugal",
    countryName_KR: "포르투갈",
    countryCode: "PT",
  },
  {
    id: 185,
    countryName: "Palau",
    countryName_KR: "팔라우",
    countryCode: "PW",
  },
  {
    id: 186,
    countryName: "Paraguay",
    countryName_KR: "파라과이",
    countryCode: "PY",
  },
  {
    id: 187,
    countryName: "Qatar",
    countryName_KR: "카타르",
    countryCode: "QA",
  },
  {
    id: 188,
    countryName: "Réunion",
    countryName_KR: "레위니옹",
    countryCode: "RE",
  },
  {
    id: 189,
    countryName: "Romania",
    countryName_KR: "루마니아",
    countryCode: "RO",
  },
  {
    id: 190,
    countryName: "Serbia",
    countryName_KR: "세르비아",
    countryCode: "RS",
  },
  {
    id: 191,
    countryName: "Russia",
    countryName_KR: "러시아",
    countryCode: "RU",
  },
  {
    id: 192,
    countryName: "Rwanda",
    countryName_KR: "르완다",
    countryCode: "RW",
  },
  {
    id: 193,
    countryName: "Saudi Arabia",
    countryName_KR: "사우디아라비아",
    countryCode: "SA",
  },
  {
    id: 194,
    countryName: "Solomon Islands",
    countryName_KR: "솔로몬 제도",
    countryCode: "SB",
  },
  {
    id: 195,
    countryName: "Seychelles",
    countryName_KR: "세이셸",
    countryCode: "SC",
  },
  { id: 196, countryName: "means", countryName_KR: "수단", countryCode: "SD" },
  {
    id: 197,
    countryName: "Sweden",
    countryName_KR: "스웨덴",
    countryCode: "SE",
  },
  {
    id: 198,
    countryName: "Singapore",
    countryName_KR: "싱가포르",
    countryCode: "SG",
  },
  {
    id: 199,
    countryName: "Saint Helena",
    countryName_KR: "세인트헬레나",
    countryCode: "SH",
  },
  {
    id: 200,
    countryName: "Slovenia",
    countryName_KR: "슬로베니아",
    countryCode: "SI",
  },
  {
    id: 201,
    countryName: "Svalbard Jan Mayen",
    countryName_KR: "스발바르 얀마옌",
    countryCode: "SJ",
  },
  {
    id: 202,
    countryName: "Slovakia",
    countryName_KR: "슬로바키아",
    countryCode: "SK",
  },
  {
    id: 203,
    countryName: "Sierra Leone",
    countryName_KR: "시에라리온",
    countryCode: "SL",
  },
  {
    id: 204,
    countryName: "San Marino",
    countryName_KR: "산마리노",
    countryCode: "SM",
  },
  {
    id: 205,
    countryName: "Senegal",
    countryName_KR: "세네갈",
    countryCode: "SN",
  },
  {
    id: 206,
    countryName: "Somalia",
    countryName_KR: "소말리아",
    countryCode: "SO",
  },
  {
    id: 207,
    countryName: "Suriname",
    countryName_KR: "수리남",
    countryCode: "SR",
  },
  {
    id: 208,
    countryName: "South Sudan",
    countryName_KR: "남수단",
    countryCode: "SS",
  },
  {
    id: 209,
    countryName: "Top-to-me Principe",
    countryName_KR: "상투메 프린시페",
    countryCode: "ST",
  },
  {
    id: 210,
    countryName: "El Salvador",
    countryName_KR: "엘살바도르",
    countryCode: "SV",
  },
  {
    id: 211,
    countryName: "Sint Marton",
    countryName_KR: "신트마르턴",
    countryCode: "SX",
  },
  {
    id: 212,
    countryName: "Syria",
    countryName_KR: "시리아",
    countryCode: "SY",
  },
  {
    id: 213,
    countryName: "Eswatini",
    countryName_KR: "에스와티니",
    countryCode: "SZ",
  },
  {
    id: 214,
    countryName: "Turks and Caicos Islands",
    countryName_KR: "터크스 케이커스 제도",
    countryCode: "TC",
  },
  { id: 215, countryName: "Chad", countryName_KR: "차드", countryCode: "TD" },
  {
    id: 216,
    countryName: "French Southern and Antarctic regions",
    countryName_KR: "프랑스령 남방 및 남극 지역",
    countryCode: "TF",
  },
  { id: 217, countryName: "Togo", countryName_KR: "토고", countryCode: "TG" },
  {
    id: 218,
    countryName: "Thailand",
    countryName_KR: "태국",
    countryCode: "TH",
  },
  {
    id: 219,
    countryName: "Tajikistan",
    countryName_KR: "타지키스탄",
    countryCode: "TJ",
  },
  {
    id: 220,
    countryName: "Tokelau, United States of America",
    countryName_KR: "토켈라우",
    countryCode: "TK",
  },
  {
    id: 221,
    countryName: "East Timor",
    countryName_KR: "동티모르",
    countryCode: "TL",
  },
  {
    id: 222,
    countryName: "Turkmenistan",
    countryName_KR: "투르크메니스탄",
    countryCode: "TM",
  },
  {
    id: 223,
    countryName: "Tunisia",
    countryName_KR: "튀니지",
    countryCode: "TN",
  },
  {
    id: 224,
    countryName: "Tonga (Korean traditional song)",
    countryName_KR: "통가",
    countryCode: "TO",
  },
  {
    id: 225,
    countryName: "Turkiye",
    countryName_KR: "튀르키예",
    countryCode: "TR",
  },
  {
    id: 226,
    countryName: "Trinidad and Tobago",
    countryName_KR: "트리니다드 토바고",
    countryCode: "TT",
  },
  {
    id: 227,
    countryName: "Tuvalu",
    countryName_KR: "투발루",
    countryCode: "TV",
  },
  {
    id: 228,
    countryName: "Republic of China",
    countryName_KR: "중화민국",
    countryCode: "TW",
  },
  {
    id: 229,
    countryName: "Tanzania",
    countryName_KR: "탄자니아",
    countryCode: "TZ",
  },
  {
    id: 230,
    countryName: "Ukraine",
    countryName_KR: "우크라이나",
    countryCode: "UA",
  },
  {
    id: 231,
    countryName: "Uganda",
    countryName_KR: "우간다",
    countryCode: "UG",
  },
  {
    id: 232,
    countryName: "the U.S. minor system",
    countryName_KR: "미국령 군소 제도",
    countryCode: "UM",
  },
  {
    id: 233,
    countryName: "the United States",
    countryName_KR: "미국",
    countryCode: "US",
  },
  {
    id: 234,
    countryName: "Uruguay",
    countryName_KR: "우루과이",
    countryCode: "UY",
  },
  {
    id: 235,
    countryName: "Uzbekistan",
    countryName_KR: "우즈베키스탄",
    countryCode: "UZ",
  },
  {
    id: 236,
    countryName: "Vatican City",
    countryName_KR: "바티칸 시국",
    countryCode: "VA",
  },
  {
    id: 237,
    countryName: "Saint Vincent and the Grenadines",
    countryName_KR: "세인트빈센트 그레나딘",
    countryCode: "VC",
  },
  {
    id: 238,
    countryName: "Venezuela",
    countryName_KR: "베네수엘라",
    countryCode: "VE",
  },
  {
    id: 239,
    countryName: "British Virgin Islands",
    countryName_KR: "영국령 버진아일랜드",
    countryCode: "VG",
  },
  {
    id: 240,
    countryName: "United States Virgin Islands",
    countryName_KR: "미국령 버진아일랜드",
    countryCode: "VI",
  },
  {
    id: 241,
    countryName: "Vietnam",
    countryName_KR: "베트남",
    countryCode: "VN",
  },
  {
    id: 242,
    countryName: "Vanuatu",
    countryName_KR: "바누아투",
    countryCode: "VU",
  },
  {
    id: 243,
    countryName: "Wallis Putuna",
    countryName_KR: "왈리스 푸투나",
    countryCode: "WF",
  },
  {
    id: 244,
    countryName: "Samoa",
    countryName_KR: "사모아",
    countryCode: "WS",
  },
  { id: 245, countryName: "Yemen", countryName_KR: "예멘", countryCode: "YE" },
  {
    id: 246,
    countryName: "Mayotte",
    countryName_KR: "마요트",
    countryCode: "YT",
  },
  {
    id: 247,
    countryName: "South Africa",
    countryName_KR: "남아프리카 공화국",
    countryCode: "ZA",
  },
  {
    id: 248,
    countryName: "Zambia",
    countryName_KR: "잠비아",
    countryCode: "ZM",
  },
  {
    id: 249,
    countryName: "Zimbabwe",
    countryName_KR: "짐바브웨",
    countryCode: "ZW",
  },
];
