export const countryData=[
    {countryName:'Afghanistan',countryName_KR:'아프가니스탄',countryCode:'AF'},
    {countryName:'Albania',countryName_KR:'알바니아',countryCode:'AL'},
    {countryName:'Antarctica',countryName_KR:'남극대륙',countryCode:'AQ'},
    {countryName:'Algeria',countryName_KR:'알제리',countryCode:'DZ'},
    {countryName:'American Samoa',countryName_KR:'아메리칸 사모아',countryCode:'AS'},
    {countryName:'Andorra',countryName_KR:'안도라',countryCode:'AD'},
    {countryName:'Angola',countryName_KR:'앙골라',countryCode:'AO'},
    {countryName:'Antigua and Barbuda',countryName_KR:'앤티가 바부다',countryCode:'AG'},
    {countryName:'Azerbaijan',countryName_KR:'아제르바이잔',countryCode:'AZ'},
    {countryName:'Argentina',countryName_KR:'아르헨티나',countryCode:'AR'},
    {countryName:'Australia',countryName_KR:'호주.',countryCode:'AU'},
    {countryName:'Austria',countryName_KR:'오스트리아',countryCode:'AT'},
    {countryName:'The Bahamas',countryName_KR:'바하마',countryCode:'BS'},
    {countryName:'Bahrain',countryName_KR:'바레인',countryCode:'BH'},
    {countryName:'Bangladesh',countryName_KR:'방글라데시',countryCode:'BD'},
    {countryName:'Armenia',countryName_KR:'아르메니아',countryCode:'AM'},
    {countryName:'Barbados',countryName_KR:'바베이도스',countryCode:'BB'},
    {countryName:'Belgium',countryName_KR:'벨기에',countryCode:'BE'},
    {countryName:'Bhutan',countryName_KR:'부탄',countryCode:'BT'},
    {countryName:'Bolivia',countryName_KR:'볼리비아',countryCode:'BO'},
    {countryName:'Bosnia and Herzegovina',countryName_KR:'보스니아 헤르체고비나',countryCode:'BA'},
    {countryName:'Botswana',countryName_KR:'보츠와나',countryCode:'BW'},
    {countryName:'Brazil',countryName_KR:'브라질',countryCode:'BR'},
    {countryName:'Belize',countryName_KR:'벨리즈',countryCode:'BZ'},
    {countryName:'Solomon Islands',countryName_KR:'솔로몬 제도',countryCode:'SB'},
    {countryName:'Brunei',countryName_KR:'브루나이',countryCode:'BN'},
    {countryName:'Bulgaria',countryName_KR:'불가리아',countryCode:'BG'},
    {countryName:'Myanmar (Burma)',countryName_KR:'미얀마 (버마)',countryCode:'MM'},
    {countryName:'Burundi',countryName_KR:'부룬디',countryCode:'BI'},
    {countryName:'Belarus',countryName_KR:'벨라루스',countryCode:'BY'},
    {countryName:'Cambodia',countryName_KR:'캄보디아',countryCode:'KH'},
    {countryName:'Cameroon',countryName_KR:'카메룬',countryCode:'CM'},
    {countryName:'Canada',countryName_KR:'캐나다',countryCode:'CA'},
    {countryName:'Cabo Verde',countryName_KR:'카보베르데',countryCode:'CV'},
    {countryName:'Central African Republic',countryName_KR:'중앙아프리카 공화국',countryCode:'CF'},
    {countryName:'Sri Lanka',countryName_KR:'스리랑카',countryCode:'LK'},
    {countryName:'Chad',countryName_KR:'차드',countryCode:'TD'},
    {countryName:'Chile',countryName_KR:'칠리',countryCode:'CL'},
    {countryName:'China',countryName_KR:'중국',countryCode:'CN'},
    {countryName:'Christmas Island',countryName_KR:'크리스마스 섬',countryCode:'CX'},
    {countryName:'Cocos (Keeling) Islands',countryName_KR:'코코스 제도',countryCode:'CC'},
    {countryName:'Colombia',countryName_KR:'콜롬비아',countryCode:'CO'},
    {countryName:'Comoros',countryName_KR:'코모로',countryCode:'KM'},
    {countryName:'Republic of the Congo',countryName_KR:'콩고 공화국',countryCode:'CG'},
    {countryName:'Democratic Republic of the Congo',countryName_KR:'콩고 민주 공화국',countryCode:'CD'},
    {countryName:'Cook Islands',countryName_KR:'쿡 제도',countryCode:'CK'},
    {countryName:'Costa Rica',countryName_KR:'코스타리카',countryCode:'CR'},
    {countryName:'Croatia',countryName_KR:'크로아티아',countryCode:'HR'},
    {countryName:'Cyprus',countryName_KR:'키프로스',countryCode:'CY'},
    {countryName:'Czechia',countryName_KR:'체코어',countryCode:'CZ'},
    {countryName:'Benin',countryName_KR:'베냉',countryCode:'BJ'},
    {countryName:'Denmark',countryName_KR:'덴마크',countryCode:'DK'},
    {countryName:'Dominica',countryName_KR:'도미니카',countryCode:'DM'},
    {countryName:'Dominican Republic',countryName_KR:'도미니카 공화국',countryCode:'DO'},
    {countryName:'Ecuador',countryName_KR:'에콰도르',countryCode:'EC'},
    {countryName:'El Salvador',countryName_KR:'엘살바도르',countryCode:'SV'},
    {countryName:'Equatorial Guinea',countryName_KR:'적도 기니',countryCode:'GQ'},
    {countryName:'Ethiopia',countryName_KR:'에티오피아',countryCode:'ET'},
    {countryName:'Eritrea',countryName_KR:'에리트레아',countryCode:'ER'},
    {countryName:'Estonia',countryName_KR:'에스토니아',countryCode:'EE'},
    {countryName:'South Georgia and the South Sandwich Islands',countryName_KR:'사우스조지아 사우스샌드위치 제도',countryCode:'GS'},
    {countryName:'Fiji',countryName_KR:'피지',countryCode:'FJ'},
    {countryName:'Finland',countryName_KR:'핀란드',countryCode:'FI'},
    {countryName:'France',countryName_KR:'프랑스.',countryCode:'FR'},
    {countryName:'French Polynesia',countryName_KR:'프랑스령 폴리네시아',countryCode:'PF'},
    {countryName:'French Southern and Antarctic Lands',countryName_KR:'프랑스 남부와 남극 대륙',countryCode:'TF'},
    {countryName:'Djibouti',countryName_KR:'지부티',countryCode:'DJ'},
    {countryName:'Gabon',countryName_KR:'가봉',countryCode:'GA'},
    {countryName:'Georgia',countryName_KR:'조지아',countryCode:'GE'},
    {countryName:'The Gambia',countryName_KR:'감비아',countryCode:'GM'},
    {countryName:'Germany',countryName_KR:'독일.',countryCode:'DE'},
    {countryName:'Ghana',countryName_KR:'가나',countryCode:'GH'},
    {countryName:'Kiribati',countryName_KR:'키리바시',countryCode:'KI'},
    {countryName:'Greece',countryName_KR:'그리스',countryCode:'GR'},
    {countryName:'Grenada',countryName_KR:'그레나다',countryCode:'GD'},
    {countryName:'Guam',countryName_KR:'괌',countryCode:'GU'},
    {countryName:'Guatemala',countryName_KR:'과테말라',countryCode:'GT'},
    {countryName:'Guinea',countryName_KR:'기니',countryCode:'GN'},
    {countryName:'Guyana',countryName_KR:'가이아나',countryCode:'GY'},
    {countryName:'Haiti',countryName_KR:'아이티',countryCode:'HT'},
    {countryName:'Heard Island and McDonald Islands',countryName_KR:'허드아일랜드와 맥도널드 제도',countryCode:'HM'},
    {countryName:'Vatican City',countryName_KR:'바티칸 시국',countryCode:'VA'},
    {countryName:'Honduras',countryName_KR:'온두라스',countryCode:'HN'},
    {countryName:'Hungary',countryName_KR:'헝가리',countryCode:'HU'},
    {countryName:'Iceland',countryName_KR:'아이슬란드',countryCode:'IS'},
    {countryName:'India',countryName_KR:'인도',countryCode:'IN'},
    {countryName:'Indonesia',countryName_KR:'인도네시아',countryCode:'ID'},
    {countryName:'Iraq',countryName_KR:'이라크',countryCode:'IQ'},
    {countryName:'Ireland',countryName_KR:'아일랜드',countryCode:'IE'},
    {countryName:'Israel',countryName_KR:'이스라엘',countryCode:'IL'},
    {countryName:'Italy',countryName_KR:'이탈리아',countryCode:'IT'},
    {countryName:'Cote d'Ivoire',countryName_KR:'Cote d'Ivoire',countryCode:'CI'},
    {countryName:'Jamaica',countryName_KR:'자메이카',countryCode:'JM'},
    {countryName:'Japan',countryName_KR:'일본',countryCode:'JP'},
    {countryName:'Kazakhstan',countryName_KR:'카자흐스탄',countryCode:'KZ'},
    {countryName:'Jordan',countryName_KR:'조던',countryCode:'JO'},
    {countryName:'Kenya',countryName_KR:'케냐',countryCode:'KE'},
    {countryName:'South Korea',countryName_KR:'대한민국.',countryCode:'KR'},
    {countryName:'Kuwait',countryName_KR:'쿠웨이트',countryCode:'KW'},
    {countryName:'Kyrgyzstan',countryName_KR:'키르기스스탄',countryCode:'KG'},
    {countryName:'Laos',countryName_KR:'라오스',countryCode:'LA'},
    {countryName:'Lebanon',countryName_KR:'레바논',countryCode:'LB'},
    {countryName:'Lesotho',countryName_KR:'레소토',countryCode:'LS'},
    {countryName:'Latvia',countryName_KR:'라트비아',countryCode:'LV'},
    {countryName:'Liberia',countryName_KR:'라이베리아',countryCode:'LR'},
    {countryName:'Libya',countryName_KR:'리비아',countryCode:'LY'},
    {countryName:'Liechtenstein',countryName_KR:'리히텐슈타인',countryCode:'LI'},
    {countryName:'Lithuania',countryName_KR:'리투아니아',countryCode:'LT'},
    {countryName:'Luxembourg',countryName_KR:'룩셈부르크',countryCode:'LU'},
    {countryName:'Madagascar',countryName_KR:'마다가스카르.',countryCode:'MG'},
    {countryName:'Malawi',countryName_KR:'말라위',countryCode:'MW'},
    {countryName:'Malaysia',countryName_KR:'말레이시아',countryCode:'MY'},
    {countryName:'Maldives',countryName_KR:'몰디브',countryCode:'MV'},
    {countryName:'Mali',countryName_KR:'말리',countryCode:'ML'},
    {countryName:'Malta',countryName_KR:'몰타',countryCode:'MT'},
    {countryName:'Mauritania',countryName_KR:'모리타니',countryCode:'MR'},
    {countryName:'Mauritius',countryName_KR:'모리셔스',countryCode:'MU'},
    {countryName:'Mexico',countryName_KR:'멕시코',countryCode:'MX'},
    {countryName:'Monaco',countryName_KR:'모나코',countryCode:'MC'},
    {countryName:'Mongolia',countryName_KR:'몽골',countryCode:'MN'},
    {countryName:'Moldova',countryName_KR:'몰도바',countryCode:'MD'},
    {countryName:'Montenegro',countryName_KR:'몬테네그로',countryCode:'ME'},
    {countryName:'Morocco',countryName_KR:'모로코',countryCode:'MA'},
    {countryName:'Mozambique',countryName_KR:'모잠비크',countryCode:'MZ'},
    {countryName:'Oman',countryName_KR:'오만',countryCode:'OM'},
    {countryName:'Namibia',countryName_KR:'나미비아',countryCode:'NA'},
    {countryName:'Nauru',countryName_KR:'나우루',countryCode:'NR'},
    {countryName:'Nepal',countryName_KR:'네팔',countryCode:'NP'},
    {countryName:'Netherlands',countryName_KR:'네덜란드',countryCode:'NL'},
    {countryName:'Curacao',countryName_KR:'쿠라카오',countryCode:'CW'},
    {countryName:'Sint Maarten',countryName_KR:'Sint Maarten',countryCode:'SX'},
    {countryName:'Caribbean Netherlands',countryName_KR:'카리브 네덜란드',countryCode:'BQ'},
    {countryName:'New Caledonia',countryName_KR:'뉴칼레도니아',countryCode:'NC'},
    {countryName:'Vanuatu',countryName_KR:'바누아투',countryCode:'VU'},
    {countryName:'New Zealand',countryName_KR:'뉴질랜드',countryCode:'NZ'},
    {countryName:'Nicaragua',countryName_KR:'니카라과',countryCode:'NI'},
    {countryName:'Niger',countryName_KR:'니제르',countryCode:'NE'},
    {countryName:'Nigeria',countryName_KR:'나이지리아',countryCode:'NG'},
    {countryName:'Niue',countryName_KR:'니우에',countryCode:'NU'},
    {countryName:'Norfolk Island',countryName_KR:'노퍽 섬',countryCode:'NF'},
    {countryName:'Norway',countryName_KR:'노르웨이',countryCode:'NO'},
    {countryName:'Northern Mariana Islands',countryName_KR:'북마리아나 제도',countryCode:'MP'},
    {countryName:'United States Minor Outlying Islands',countryName_KR:'미국의 작은 외딴 섬들',countryCode:'UM'},
    {countryName:'Micronesia',countryName_KR:'미크로네시아',countryCode:'FM'},
    {countryName:'Marshall Islands',countryName_KR:'마셜 제도',countryCode:'MH'},
    {countryName:'Palau',countryName_KR:'팔라우',countryCode:'PW'},
    {countryName:'Pakistan',countryName_KR:'파키스탄',countryCode:'PK'},
    {countryName:'Panama',countryName_KR:'파나마',countryCode:'PA'},
    {countryName:'Papua New Guinea',countryName_KR:'파푸아뉴기니',countryCode:'PG'},
    {countryName:'Paraguay',countryName_KR:'파라과이',countryCode:'PY'},
    {countryName:'Peru',countryName_KR:'페루',countryCode:'PE'},
    {countryName:'Philippines',countryName_KR:'필리핀',countryCode:'PH'},
    {countryName:'Pitcairn Islands',countryName_KR:'핏케언 제도',countryCode:'PN'},
    {countryName:'Poland',countryName_KR:'폴란드',countryCode:'PL'},
    {countryName:'Portugal',countryName_KR:'포르투갈',countryCode:'PT'},
    {countryName:'Guinea-Bissau',countryName_KR:'기니비사우',countryCode:'GW'},
    {countryName:'Timor-Leste',countryName_KR:'동티모르',countryCode:'TL'},
    {countryName:'Qatar',countryName_KR:'카타르',countryCode:'QA'},
    {countryName:'Romania',countryName_KR:'루마니아',countryCode:'RO'},
    {countryName:'Russia',countryName_KR:'러시아',countryCode:'RU'},
    {countryName:'Rwanda',countryName_KR:'르완다',countryCode:'RW'},
    {countryName:'Saint Barthelemy',countryName_KR:'성 바르텔레미',countryCode:'BL'},
    {countryName:'Saint Helena, Ascension and Tristan da Cunha',countryName_KR:'성 헬레나, 승천과 트리스탄 다 쿠냐',countryCode:'SH'},
    {countryName:'Saint Kitts and Nevis',countryName_KR:'세인트키츠 네비스',countryCode:'KN'},
    {countryName:'Saint Lucia',countryName_KR:'세인트루시아',countryCode:'LC'},
    {countryName:'Saint Martin',countryName_KR:'세인트 마틴',countryCode:'MF'},
    {countryName:'Saint Pierre and Miquelon',countryName_KR:'생 피에르 미켈론',countryCode:'PM'},
    {countryName:'Saint Vincent and the Grenadines',countryName_KR:'세인트빈센트 그레나딘',countryCode:'VC'},
    {countryName:'San Marino',countryName_KR:'산마리노',countryCode:'SM'},
    {countryName:'Sao Tome and Principe',countryName_KR:'상투메와 프린시페',countryCode:'ST'},
    {countryName:'Saudi Arabia',countryName_KR:'사우디아라비아',countryCode:'SA'},
    {countryName:'Senegal',countryName_KR:'세네갈',countryCode:'SN'},
    {countryName:'Serbia',countryName_KR:'세르비아',countryCode:'RS'},
    {countryName:'Seychelles',countryName_KR:'세이셸',countryCode:'SC'},
    {countryName:'Sierra Leone',countryName_KR:'시에라리온',countryCode:'SL'},
    {countryName:'Singapore',countryName_KR:'싱가포르',countryCode:'SG'},
    {countryName:'Slovakia',countryName_KR:'슬로바키아',countryCode:'SK'},
    {countryName:'Vietnam',countryName_KR:'베트남',countryCode:'VN'},
    {countryName:'Slovenia',countryName_KR:'슬로베니아',countryCode:'SI'},
    {countryName:'Somalia',countryName_KR:'소말리아',countryCode:'SO'},
    {countryName:'South Africa',countryName_KR:'남아프리카 공화국',countryCode:'ZA'},
    {countryName:'Zimbabwe',countryName_KR:'짐바브웨',countryCode:'ZW'},
    {countryName:'Spain',countryName_KR:'스페인',countryCode:'ES'},
    {countryName:'South Sudan',countryName_KR:'남수단',countryCode:'SS'},
    {countryName:'Sudan',countryName_KR:'수단',countryCode:'SD'},
    {countryName:'Suriname',countryName_KR:'수리남',countryCode:'SR'},
    {countryName:'Eswatini',countryName_KR:'에스와티니',countryCode:'SZ'},
    {countryName:'Sweden',countryName_KR:'스웨덴',countryCode:'SE'},
    {countryName:'Switzerland',countryName_KR:'스위스',countryCode:'CH'},
    {countryName:'Tajikistan',countryName_KR:'타지키스탄',countryCode:'TJ'},
    {countryName:'Thailand',countryName_KR:'태국.',countryCode:'TH'},
    {countryName:'Togo',countryName_KR:'포장이요',countryCode:'TG'},
    {countryName:'Tokelau',countryName_KR:'토켈라우',countryCode:'TK'},
    {countryName:'Tonga',countryName_KR:'통가',countryCode:'TO'},
    {countryName:'Trinidad and Tobago',countryName_KR:'트리니다드 토바고',countryCode:'TT'},
    {countryName:'United Arab Emirates',countryName_KR:'아랍에미리트',countryCode:'AE'},
    {countryName:'Tunisia',countryName_KR:'튀니지',countryCode:'TN'},
    {countryName:'Turkiye',countryName_KR:'튀르키예',countryCode:'TR'},
    {countryName:'Turkmenistan',countryName_KR:'투르크메니스탄',countryCode:'TM'},
    {countryName:'Tuvalu',countryName_KR:'투발루',countryCode:'TV'},
    {countryName:'Uganda',countryName_KR:'우간다',countryCode:'UG'},
    {countryName:'Ukraine',countryName_KR:'우크라이나',countryCode:'UA'},
    {countryName:'North Macedonia',countryName_KR:'북마케도니아',countryCode:'MK'},
    {countryName:'Egypt',countryName_KR:'이집트',countryCode:'EG'},
    {countryName:'United Kingdom',countryName_KR:'영국',countryCode:'GB'},
    {countryName:'Guernsey',countryName_KR:'건지',countryCode:'GG'},
    {countryName:'Jersey',countryName_KR:'저지',countryCode:'JE'},
    {countryName:'Isle of Man',countryName_KR:'맨섬',countryCode:'IM'},
    {countryName:'Tanzania',countryName_KR:'탄자니아',countryCode:'TZ'},
    {countryName:'United States',countryName_KR:'미국',countryCode:'US'},
    {countryName:'Burkina Faso',countryName_KR:'부르키나파소',countryCode:'BF'},
    {countryName:'Uruguay',countryName_KR:'우루과이',countryCode:'UY'},
    {countryName:'Uzbekistan',countryName_KR:'우즈베키스탄',countryCode:'UZ'},
    {countryName:'Venezuela',countryName_KR:'베네수엘라',countryCode:'VE'},
    {countryName:'Wallis and Futuna',countryName_KR:'왈리스와 후투나',countryCode:'WF'},
    {countryName:'Samoa',countryName_KR:'사모아',countryCode:'WS'},
    {countryName:'Yemen',countryName_KR:'예멘',countryCode:'YE'},
    {countryName:'Zambia',countryName_KR:'잠비아',countryCode:'ZM'},
]